"""
Gemini Recommendation Service for RiskGuard.
Integrates Google Generative AI (Gemini 1.5 Flash) to synthesize actionable,
context-rich mitigation strategies driven by ML risk scores and SHAP feature drivers.
"""

import os
from typing import Dict, Any, List, Optional
import google.generativeai as genai

# Supported and active model identifiers
DEFAULT_GEMINI_MODEL = "gemini-flash-latest"
CANDIDATE_GEMINI_MODELS = ["gemini-flash-latest", "gemini-pro-latest", "gemini-2.5-pro"]


def build_recommendation_prompt(
    project_name: str,
    sector: str,
    state: str,
    delay_probability: float,
    risk_score: float,
    risk_category: str,
    top_risk_factors: List[str],
    top_mitigating_factors: Optional[List[str]] = None,
    custom_context: Optional[str] = None
) -> str:
    """
    Constructs an analytical, domain-aware prompt embedding ML predictions and SHAP attributions.
    """
    factors_str = "\n".join([f"  - {factor}" for factor in top_risk_factors]) if top_risk_factors else "  - Not available"
    mitigating_str = "\n".join([f"  - {factor}" for factor in top_mitigating_factors]) if top_mitigating_factors else "  - Not available"

    prompt = f"""You are the chief infrastructure risk advisor on the RiskGuard system for Indian national and state infrastructure initiatives.

Analyze the following project assessment generated by our machine learning and SHAP explainability pipeline:

==================== PROJECT PROFILE ====================
Project Name: {project_name}
Sector: {sector}
Location: {state}
Delay Probability: {delay_probability:.2%}
Risk Score: {risk_score:.1f} / 100
Risk Category: {risk_category}

================ KEY SHAP DELAY CONTRIBUTORS ================
The ML model identified these top factors driving UP the predicted delay risk:
{factors_str}

================ KEY MITIGATING FACTORS ================
Factors currently helping keep delay risk lower:
{mitigating_str}
"""
    if custom_context:
        prompt += f"\nAdditional Field Context: {custom_context}\n"

    prompt += f"""
================ REQUIRED OUTPUT ================
Provide exactly 3 to 4 concise, high-impact, actionable recommendations for project managers and governing authorities to mitigate these specific delay bottlenecks.
Each recommendation must:
1. Address an identified risk driver (e.g. expenditure-to-progress gap, legal disputes, regional power/clearance constraints, or schedule overruns).
2. Propose concrete operational, financial, or administrative actions.
3. Be direct, authoritative, and professional.

Format as a bulleted list starting with '- '."""
    return prompt


def generate_gemini_recommendations(
    project_name: str,
    sector: str,
    state: str,
    delay_probability: float,
    risk_score: float,
    risk_category: str,
    top_risk_factors: List[str],
    top_mitigating_factors: Optional[List[str]] = None,
    custom_context: Optional[str] = None
) -> Dict[str, Any]:
    """
    Invokes Google Gemini API with analytical context, or falls back to
    deterministic domain heuristics if the API key is not configured.
    """
    api_key = os.getenv("GEMINI_API_KEY")

    prompt = build_recommendation_prompt(
        project_name=project_name,
        sector=sector,
        state=state,
        delay_probability=delay_probability,
        risk_score=risk_score,
        risk_category=risk_category,
        top_risk_factors=top_risk_factors,
        top_mitigating_factors=top_mitigating_factors,
        custom_context=custom_context
    )

    if not api_key or api_key.strip() in ("", "your_gemini_api_key_here"):
        # Graceful domain-driven fallback when no API key is supplied
        fallback_recs = generate_heuristic_recommendations(risk_category, top_risk_factors)
        return {
            "recommendations": fallback_recs,
            "model_used": "domain-heuristic-fallback",
            "status": "offline_fallback",
            "notes": "GEMINI_API_KEY not configured. Set GEMINI_API_KEY in .env for live AI generation."
        }

    try:
        genai.configure(api_key=api_key)
        response = None
        used_model = DEFAULT_GEMINI_MODEL
        for model_name in CANDIDATE_GEMINI_MODELS:
            try:
                model = genai.GenerativeModel(model_name)
                response = model.generate_content(prompt)
                used_model = model_name
                break
            except Exception:
                continue

        if response is None:
            raise RuntimeError("None of the candidate Gemini models were reachable.")

        text = response.text.strip()

        # Parse bullets into list
        recs = [line.lstrip("-* ").strip() for line in text.split("\n") if line.strip().startswith(("-", "*", "1.", "2.", "3.", "4."))]
        if not recs:
            recs = [line.strip() for line in text.split("\n") if len(line.strip()) > 15]

        return {
            "recommendations": recs[:4] if recs else [text],
            "model_used": used_model,
            "status": "gemini_live",
            "notes": None
        }
    except Exception as e:
        # Fallback on network or auth failure
        fallback_recs = generate_heuristic_recommendations(risk_category, top_risk_factors)
        return {
            "recommendations": fallback_recs,
            "model_used": "domain-heuristic-fallback",
            "status": "error_fallback",
            "notes": f"Gemini API request failed ({str(e)}). Returned domain heuristic recommendations."
        }


def generate_heuristic_recommendations(risk_category: str, top_factors: List[str]) -> List[str]:
    """Generates deterministic domain recommendations based on risk category and drivers."""
    recs = []
    top_lower = [f.lower() for f in top_factors]

    if any("expenditure" in f or "cost" in f for f in top_lower):
        recs.append("Conduct an immediate joint financial-physical milestone audit to reconcile the expenditure-to-progress ratio.")
    
    if any("duration" in f or "schedule" in f for f in top_lower):
        recs.append("Implement critical-path fast-tracking and enforce contractor liquidated damages clauses for lagging sub-packages.")

    if any("court" in f or "case" in f or "legal" in f for f in top_lower):
        recs.append("Engage with the State High Court land acquisition tribunal to fast-track stay order resolutions and compensation settlements.")

    if any("power" in f or "energy" in f for f in top_lower):
        recs.append("Coordinate with state electricity distribution companies (DISCOMs) to secure dedicated feeder lines for construction works.")

    # General recommendations if specific triggers are missing
    if len(recs) < 3:
        if risk_category == "HIGH":
            recs.append("Establish a weekly Empowered Committee taskforce under the State Chief Secretary for inter-departmental clearances.")
            recs.append("Issue contractual show-cause notices for milestone delays exceeding 60 days.")
        elif risk_category == "MEDIUM":
            recs.append("Institute bi-weekly progress reviews with the Project Management Consultant (PMC).")
            recs.append("Review vendor supply chain lead times for critical materials.")
        else:
            recs.append("Maintain routine monthly milestone verification and standard quality control audits.")

    return recs[:4]
